providers:
  - name: namecheap
    domain: example.com
    host: "@"
    password: e5322165c1d74692bfa6d807100c0310
    
  - name: cloudflare
    zone_identifier: id
    domain: domain.com
    host: "@"
    ttl: 600
    token: 5s36mEYvzk
    ip_version: ipv4
